apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: gateway.club012.com
      http:
        paths:
          - path: /blue
            pathType: Prefix
            backend:
              service:
                name: nginx-blue-external
                port:
                  number: 80
          - path: /red
            pathType: Prefix
            backend:
              service:
                name: nginx-red-external
                port:
                  number: 80
          - path: /black
            pathType: Prefix
            backend:
              service:
                name: nginx-black-external
                port:
                  number: 80
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nginx-gateway
                port:
                  number: 80
