apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-blue-external
spec:
  clusterIP: None
  # {Service Name}.{Namespace}.svc.cluster.local 형식으로 작성
  externalName: nginx-blue.blue.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-red-external
spec:
  clusterIP: None
  externalName: nginx-red.red.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-black-external
spec:
  clusterIP: None
  externalName: nginx-black.black.svc.cluster.local
