# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-blue-external
spec:
  type: ExternalName
  # {Service Name}.{Namespace}.svc.cluster.local 형식으로 작성
  externalName: nginx-blue.blue.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-red-external
spec:
  type: ExternalName
  externalName: nginx-red.red.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-black-external
spec:
  type: ExternalName
  externalName: nginx-black.black.svc.cluster.local
