apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-blue-external
spec:
  type: ExternalName
  # {Service Name}.{Namespace}.svc.cluster.local 형식으로 작성
  externalName: nginx-blue.blue.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-red-external
spec:
  type: ExternalName
  externalName: nginx-red.red.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: nginx-black-external
spec:
  type: ExternalName
  externalName:  www.google.com
