# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-black
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.club012.com/nginxhello
        env:
        - name: COLOR
          value: black
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 80
